# Stage 1: Build the application
FROM gradle:8.10.2-jdk17 AS build
WORKDIR /app
COPY --chown=gradle:gradle . .

# Run the Gradle build with no daemon to avoid memory issues
RUN gradle build --no-daemon --stacktrace --info

# Stage 2: Run the application
FROM openjdk:17-jdk-alpine
WORKDIR /app

# Copy the built JAR file from the build stage
COPY --from=build /app/build/libs/*.jar app.jar

# Set the JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH="$JAVA_HOME/bin:$PATH"

# Expose the port your Spring Boot app will run on
EXPOSE 8080

# Run the Spring Boot app
ENTRYPOINT ["java","-jar","/app.jar"]